apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: leaselock
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create", "get", "watch", "list", "delete", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "watch", "list", "delete", "patch", "update"]